apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init.js: |
    db = db.getSiblingDB('testing');
    db.createUser({
      user: "naruto",
      pwd: "malia254",
      roles: [{ role: "readWrite", db: "testing" }]
    });