apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command: ["mongod", "--config", "/etc/mongod.conf"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
          volumeMounts:
            - name: mongo-config-volume
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-config-volume
          configMap:
            name: mongo-config
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
